### ISSUE TITLE
browserify EasyUI

### ISSUE THREAD

**Issue by ermorela** [djalbat/Easy#1]
Hi running the sample code (examples.html) everything works, but inserting it into a module through browserify something is going wrong. 
`browserify entry.js -o bundle.js` ends without errors, but elements on the page return no action on console. 
The tree is: 

```
├── bundle.css
├── bundle.js
├── conslog.js
├── css
│   ├── XXXXX.css
├── entry.js
├── index.html
├── JS
│   ├── calendar.js
│   ├── multiply.js
│   └── square.js
├── multiply.js
├── node_modules
│   ├── easyui
│   │   ├── dist
│   │   │   └── easyui.js
│   │   ├── docs
│   │   │   └── examples.html
│   │   ├── Gruntfile.js
│   │   ├── index.js
│   │   ├── lib
│   │   │   ├── body.js
│   │   │   ├── bounds.js
│   │   │   ├── button.js
│   │   │   ├── checkbox.js
│   │   │   ├── div.js
│   │   │   ├── document.js
│   │   │   ├── element.js
│   │   │   ├── inputElement.js
│   │   │   ├── input.js
│   │   │   ├── link.js
│   │   │   ├── position.js
│   │   │   ├── select.js
│   │   │   ├── textArea.js
│   │   │   └── window.js
├── package.json
├── scripts
│   └── lib
│       ├── body.js
│       ├── bounds.js
│       ├── button.js
│       ├── checkbox.js
│       ├── div.js
│       ├── document.js
│       ├── easyui.js
│       ├── element.js
│       ├── inputElement.js
│       ├── input.js
│       ├── link.js
│       ├── position.js
│       ├── select.js
│       ├── textArea.js
│       └── window.js
├── square.js
└── tootltip.js
```

entry.js

```
global.jQuery = require('jquery');
var calend = require('./JS/calendar')();
```

calendar.js

```
module.exports = function() {
var easyUI = require('../scripts/lib/easyui'),
  Element = easyUI.Element,
      Div = easyUI.Div,
      Body = easyUI.Body,
      Link = easyUI.Link,
      Input = easyUI.Input,
      Button = easyUI.Button,
      Select = easyUI.Select,
      Checkbox = easyUI.Checkbox,
      TextArea = easyUI.TextArea;

// all the rest of code from <script> </script> in examples.html

  console.log('There are ' + fourthDivParentElementsLength + ' parent elements of the fourth div');

}
```

**Comment by ghost** [comment]
Hi,

thanks for giving EasyUI a go, firstly. 

Before I try to replicate this, can I suggest that you check whether logging to the console is working at all?

Regards,

James

**Comment by ermorela** [comment]
Thank you for your code is really great! And yes if I insert a simply console.log("something") at the start of the module, exactly after `module.exports = function() {`, the console outputs correctly

**Comment by ghost** [comment]
Okay, I will take a look at this tomorrow and get back to you. It's late now.

Thanks for the compliment, much appreciated.

**Comment by djalbat** [comment]
Hi,

okay, I've had a chance to look at this. I can't pin down exactly what is going wrong, however I can offer a solution... 

The thing I found a couple of years ago with browserify is that you can't require browserified files, it just doesn't work. I keep the browserified file in the distribution so that I can include it by way of a script tag for the sake of the examples. I would never do this in a real project, however. For a real project, I would require the EasyUI library as a node module. 

I've attached a small project that will hopefully get you going. Just unzip it, run `npm install` and then `grunt build`. If you open the `index.html` file in a browser, this will reference the browserified file that's been created, which in turn executes the EasyUI example code from within your calendar function.

The choice of grunt was pretty arbitrary, I hope it works for you. I've included the necessary configuration to get you going with ES6, too.

In essence, never require browserified libraries, instead require node modules, then things should be fine.

I hope all this helps!

[temp.zip](https://github.com/djalbat/EasyUI/files/379039/temp.zip)

**Comment by ermorela** [comment]
Thanks!!!! Now I'm in a new completely fresh environment, but the problem remains the same. I guess I'm doing something wrong. I installed npm, then `npm install -g grunt-cli`, tried with `grunt build` but got the error 

> > > Local Npm module "grunt-browserify" not found. Is it installed?

Also I had to install `npm install grunt-browserify --save-dev` and finally I was able to build only invoking `grunt build --force`, but when I browse the console of my `index.html` nothing happens...

**Comment by djalbat** [comment]
Hi,

`grunt-browserify` is there in the `devDepenencies` in the `package.json` file so I've no idea why you had to install it manually. You're right about having to install `grunt-cli` globally, however. I'm sorry I forgot that and glad you worked it out.

After that I'm struggling to help you. Why did you need the `--force` flag? What happens if you leave it off?

Regards,

James

**Comment by ermorela** [comment]
Hi, thanks for your help, really precious! 
The first time i executed `grunt build` I got the message `Warning: Task "browserify" not found. Use --force to continue.` and `Aborted due to warnings.` so I installed `grunt-browserify --save-dev` hoping this solve the problem. Executing once again `grunt build` I got `Warning: Cannot find module 'babelify' from '/Applications/MAMP/htdocs/temp' Use --force to continue.` and once again `Aborted due to warnings.`. 
At the end I executed the build using `grunt build --force` and the output was `Warning: Cannot find module 'babelify' from '/Applications/MAMP/htdocs/temp' Used --force, continuing.` 
Using **--force** in some way let it go and I stopped importing bunch of modules, but the result was sadly wrong

**Comment by djalbat** [comment]
Hi,

okay, progress. It looks like you ran `grunt build` perhaps before running `npm install`, since both `grunt-browserify` and `babelify` are in the `package.json`. 

Using `--force` will not fix anything and you won't see anything in the browser until you've built the bundled file correctly.

Can I suggest that you download the temp.zip file again into a fresh folder and replace the contents of the `package.json` with the following:

```
{
  "devDependencies": {
    "easyui": "^3.5.10",
    "babel-preset-es2015": "^6.6.0",
    "babelify": "^7.3.0",
    "grunt": "^1.0.1",
    "grunt-browserify": "^5.0.0"
  }
}
```

Then run `npm install` _first_ (forgive the emphasis) and then run `grunt build`.

**Comment by ermorela** [comment]
Don't worry emphasis was necessary. I didn't run `npm install` before executing `grunt build`, I didn't get it, thought it was to execute only once. 

Now the project works correctly.

Do you mind I have to execute both at every single change in my project?  I mean before executing `grunt build` I have to run `npm install` every time ? It takes some minutes at the end ....

**Comment by djalbat** [comment]
No, you only have to run `npm install` when the dependencies change. You will have to run `npm build` every time you make a change to your own code, however. This is the curse of developing with NodeJS.

What you should do at least is set a watcher to watch your files and rebuild automatically. Have a look at the `package.json` and `grunt.js` files in the EasyUI project, you should have enough expertise now to get this set up.

Just to be clear...you now have this running properly? I'm glad if so.

**Comment by ermorela** [comment]
Perfectly! You're great. Hope this post could also help others.

**Comment by djalbat** [comment]
Many thanks. Do me a favour and star the repository if you like. Also, if you want to contribute, feel free to add some more elements. For example it would easy to add support for `footer`, `nav`, `section` and `article` elements by simply copying the `Div` class, renaming where appropriate and adding the relevant entries to the `index.js` file. It would be good if I started getting the odd pull request along these lines...

Anyway, thanks for your interest!
